version: '2'
services:
  framework-admin:
    image: framework/admin
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=dev
  framework-api:
    image: framework/api
    ports:
      - "8081:8081"
    environment:
      - spring.profiles.active=dev