package com.microservices.b2c.service.entity.model;

import com.microservices.db.annotation.Table;
import com.microservices.b2c.service.entity.model.base.BaseProduct;

/**
 * Generated by Microservices.
 */
@Table(tableName = "b2c_product", primaryKey = "id")
public class Product extends BaseProduct<Product> {

}
