package com.microservices.admin.service.entity.model;

import com.microservices.db.annotation.Table;
import com.microservices.admin.service.entity.model.base.BaseData;

/**
 * Generated by Microservices.
 */
@Table(tableName = "sys_data", primaryKey = "id")
public class Data extends BaseData<Data> {

}
