package com.microservices.admin.service.entity.model;

import com.microservices.db.annotation.Table;
import com.microservices.admin.service.entity.model.base.BaseLog;

/**
 * Generated by Microservices.
 */
@Table(tableName = "sys_log", primaryKey = "id")
public class Log extends BaseLog<Log> {

}
