package com.microservices.admin.service.entity.model;

import com.microservices.db.annotation.Table;
import com.microservices.admin.service.entity.model.base.BaseRes;

/**
 * Generated by Microservices.
 */
@Table(tableName = "sys_res", primaryKey = "id")
public class Res extends BaseRes<Res> {

}
