package com.microservices.admin.service.entity.model;

import com.microservices.db.annotation.Table;
import com.microservices.admin.service.entity.model.base.BaseRoleRes;

/**
 * Generated by Microservices.
 */
@Table(tableName = "sys_role_res", primaryKey = "id")
public class RoleRes extends BaseRoleRes<RoleRes> {

}
