package com.microservices.admin.service.entity.model;

import com.microservices.db.annotation.Table;
import com.microservices.admin.service.entity.model.base.BaseRole;

/**
 * Generated by Microservices.
 */
@Table(tableName = "sys_role", primaryKey = "id")
public class Role extends BaseRole<Role> {

}
