package com.microservices.admin.service.entity.model;

import com.microservices.db.annotation.Table;
import com.microservices.admin.service.entity.model.base.BaseUserRole;

/**
 * Generated by Microservices.
 */
@Table(tableName = "sys_user_role", primaryKey = "id")
public class UserRole extends BaseUserRole<UserRole> {

}
