package com.microservices.admin.service.entity.model;

import com.microservices.db.annotation.Table;
import com.microservices.admin.service.entity.model.base.BaseUser;

/**
 * Generated by Microservices.
 */
@Table(tableName = "sys_user", primaryKey = "id")
public class User extends BaseUser<User> {

}
